name: check bot startup

on:
  push:
    branches: [ "main","dev"]
  pull_request:
    branches: [ "main" ]

jobs: 
  running:
    name: Run bot startup check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Packages
        run: npm install

      - name: Build the bot
        env: 
          TOKEN: ${{ secrets.BOT_TOKEN }}
          DB_LOGIN: ${{ secrets.DB_LOGIN }}
        run: npm run build

      - name: Run the bot
        env: 
          TOKEN: ${{ secrets.BOT_TOKEN }}
          DB_LOGIN: ${{ secrets.DB_LOGIN }}
        run: |
          timeout 30s npm run start || EXIT_CODE=$?
          if [ $EXIT_CODE -ne 0 ] && [ $EXIT_CODE -ne 124 ]; then
            echo "Process exited with an error code $EXIT_CODE"
            exit $EXIT_CODE
          fi
        continue-on-error: true
